apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: migrate
          image: user-service:latest  # Same image as the main app container
          imagePullPolicy: IfNotPresent
          command: ["php", "artisan", "migrate", "--force"]
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_DATABASE
              value: "laravel"
            - name: QUEUE_CONNECTION
              value: "redis"
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_DATABASE
              value: "laravel"
            - name: QUEUE_CONNECTION
              value: "redis"
            - name: REDIS_CLIENT
              value: "predis"
            - name: REDIS_HOST
              value: redis
            - name: QUEUE_DEFAULT
              value: "users_event"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort